/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author cuong
 */
public class frmManHinhChinh extends javax.swing.JFrame {

    /**
     * Creates new form frmManHinhChinh
     */
    public frmManHinhChinh() {
//        init();
        initComponents();
        this.setVisible(true);
//        if (jdlLogin.role.equals("user")) {
//            btnQLNhanVien.setEnabled(false);
////                    btnKhachHang.setEnabled(false);
//            btnQLSanPham.setEnabled(false);

//        }
        setExtendedState(JFrame.MAXIMIZED_BOTH);
//        frmQLPhong frmSP = new frmQLPhong();
//        frmSP.setVisible(true);
    }

    void init() {
        openChao();
        openLogin();
    }

    void openChao() {
        new jdlHello(this, true).setVisible(true);
    }

    void openLogin() {
        new jdlLogin(this, true).setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pmnVidu = new javax.swing.JPopupMenu();
        mniThem = new javax.swing.JMenuItem();
        mniSua = new javax.swing.JMenuItem();
        tbarChuongTrinh = new javax.swing.JToolBar();
        btnQLSanPham = new javax.swing.JButton();
        btnQLNhanVien = new javax.swing.JButton();
        btnKhachHang = new javax.swing.JButton();
        btnDienNuoc = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        tabChinh = new javax.swing.JTabbedPane();
        mnbMenuChinh = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mniThoat = new javax.swing.JMenuItem();
        mnuEdit = new javax.swing.JMenu();

        mniThem.setText("Thêm sản phẩm");
        mniThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniThemActionPerformed(evt);
            }
        });
        pmnVidu.add(mniThem);

        mniSua.setText("Sửa sản phẩm");
        mniSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSuaActionPerformed(evt);
            }
        });
        pmnVidu.add(mniSua);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Phần mềm quản lý bán hàng");

        tbarChuongTrinh.setBackground(new java.awt.Color(204, 255, 255));
        tbarChuongTrinh.setRollover(true);

        btnQLSanPham.setBackground(new java.awt.Color(204, 255, 255));
        btnQLSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Library-alt-icon.png"))); // NOI18N
        btnQLSanPham.setFocusable(false);
        btnQLSanPham.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLSanPham.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQLSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLSanPhamActionPerformed(evt);
            }
        });
        tbarChuongTrinh.add(btnQLSanPham);

        btnQLNhanVien.setBackground(new java.awt.Color(204, 255, 255));
        btnQLNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Library-icon.png"))); // NOI18N
        btnQLNhanVien.setFocusable(false);
        btnQLNhanVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLNhanVienActionPerformed(evt);
            }
        });
        tbarChuongTrinh.add(btnQLNhanVien);

        btnKhachHang.setBackground(new java.awt.Color(204, 255, 255));
        btnKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Group-icon.png"))); // NOI18N
        btnKhachHang.setFocusable(false);
        btnKhachHang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKhachHang.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhachHangActionPerformed(evt);
            }
        });
        tbarChuongTrinh.add(btnKhachHang);

        btnDienNuoc.setBackground(new java.awt.Color(204, 255, 255));
        btnDienNuoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Apps-alt-icon.png"))); // NOI18N
        btnDienNuoc.setFocusable(false);
        btnDienNuoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDienNuoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDienNuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDienNuocActionPerformed(evt);
            }
        });
        tbarChuongTrinh.add(btnDienNuoc);

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Desktop-icon.png"))); // NOI18N
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        tbarChuongTrinh.add(jButton1);

        getContentPane().add(tbarChuongTrinh, java.awt.BorderLayout.NORTH);

        jPanel2.setBackground(new java.awt.Color(229, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 255)));

        tabChinh.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabChinh)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabChinh)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        mnbMenuChinh.setBackground(new java.awt.Color(153, 204, 255));

        mnuFile.setText("File");

        mniThoat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        mniThoat.setText("Thoát");
        mniThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniThoatActionPerformed(evt);
            }
        });
        mnuFile.add(mniThoat);

        mnbMenuChinh.add(mnuFile);

        mnuEdit.setText("Edit");
        mnbMenuChinh.add(mnuEdit);

        setJMenuBar(mnbMenuChinh);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mniThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniThoatActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mniThoatActionPerformed

    private void mniThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniThemActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Bạn vừa bấm nút Thêm trong popup menu");
    }//GEN-LAST:event_mniThemActionPerformed

    private void mniSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSuaActionPerformed
        JOptionPane.showMessageDialog(null, "Bạn vừa bấm nút SỬA trong popup menu");
    }//GEN-LAST:event_mniSuaActionPerformed

    private void btnKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhachHangActionPerformed
        jdlKhachHang jdlKH = new jdlKhachHang(this, true);
        jdlKH.setVisible(true);
    }//GEN-LAST:event_btnKhachHangActionPerformed
    boolean hienThiPnlThuePhong = false;
    private void btnQLNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLNhanVienActionPerformed
        //Tạo 1 đối tượng pnlQLNHanVien
        pnlQLThuePhong pnlNV = new pnlQLThuePhong();
        if (tabChinh.getTabCount() > 0) {
            tabChinh.remove(0);
            
        }
        tabChinh.add(pnlNV, "Quản lý thuê phòng");
//        if (!hienThiPnlThuePhong) {
//            hienThiPnlThuePhong = true;
//        } else {
//            hienThiPnlThuePhong = false;
//        }
    }//GEN-LAST:event_btnQLNhanVienActionPerformed

    private void btnQLSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLSanPhamActionPerformed
        //Tạo đối tượng frmQLPhong (JFrame cần hiển thị)
        frmQLPhong frmQLSP = new frmQLPhong();
        frmQLSP.setVisible(true);   //Hiển thị Jframe vừa tạo
    }//GEN-LAST:event_btnQLSanPhamActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        pnlHoaDon pnlNV = new pnlHoaDon();
        if (tabChinh.getTabCount() > 0) {
            tabChinh.remove(0);
        }
            tabChinh.add(pnlNV, "Bản ghi phiếu thu");

//        if (!hienThiPnlThuePhong) {
//            hienThiPnlThuePhong = true;
//        } else {
//            hienThiPnlThuePhong = false;
//        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnDienNuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDienNuocActionPerformed
        // TODO add your handling code here:
        jdlDienNuoc jdl = new jdlDienNuoc(this, true);
        jdl.setVisible(true);
    }//GEN-LAST:event_btnDienNuocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmManHinhChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmManHinhChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmManHinhChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmManHinhChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmManHinhChinh();

//                GraphicsEnvironment graphics = GraphicsEnvironment.getLocalGraphicsEnvironment();
//                GraphicsDevice device = graphics.getDefaultScreenDevice();
//                frmManHinhChinh frame = new frmManHinhChinh();
//                device.setFullScreenWindow(frame);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDienNuoc;
    public static javax.swing.JButton btnKhachHang;
    public static javax.swing.JButton btnQLNhanVien;
    public static javax.swing.JButton btnQLSanPham;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuBar mnbMenuChinh;
    private javax.swing.JMenuItem mniSua;
    private javax.swing.JMenuItem mniThem;
    private javax.swing.JMenuItem mniThoat;
    private javax.swing.JMenu mnuEdit;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JPopupMenu pmnVidu;
    private javax.swing.JTabbedPane tabChinh;
    private javax.swing.JToolBar tbarChuongTrinh;
    // End of variables declaration//GEN-END:variables
}
