/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DTO.*;
import helper.ChuyenDoi;
import helper.ThongBao;
import helper.XuatExcel;
import java.io.File;
import java.io.FileOutputStream;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.ss.usermodel.CreationHelper;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author cuong
 */
public class frmQLPhong extends javax.swing.JFrame {

    /**
     * Creates new form frmQLSanPham
     */
    public frmQLPhong() {
        initComponents();
        btnDocFile.setVisible(false);
//        btnXuatFile.setVisible(false);
//        btnThoat.setVisible(false);
        loadTT();
    }

    public void loadTT() {
        ArrayList<PhongTro> arr = BLL.BLLPhongTro.GetAll();
        loadTTPhongTro(arr);
        ArrayList<BangGia> arrBG = BLL.BLLBangGia.GetAll();
        loadTTBangGia(arrBG);
        ArrayList<Phong> arrP = BLL.BLLPhong.GetAll();
        BLL.BLLPhong.doDataTable(arrP, tblPhong);
    }

    public void loadTTPhongTro(ArrayList<PhongTro> arr) {
        System.out.println("hhh: " + arr.get(0).getTenPhongTro());
        txtTenPhongTro.setText(arr.get(0).getTenPhongTro());
        txtChuPhongTro.setText(arr.get(0).getChuPhongTro());
        txtSDT.setText(arr.get(0).getSDT());
        txtDiaChi.setText(arr.get(0).getDiaChi());
    }

    public void loadTTBangGia(ArrayList<BangGia> arr) {
        txtGiaPhong.setText(ChuyenDoi.SoString(arr.get(0).getGiaPhong()));
        txtGiaDien.setText(ChuyenDoi.SoString(arr.get(0).getGiaDien()));
        txtGiaNuoc.setText(ChuyenDoi.SoString(arr.get(0).getGiaNuoc()));
        txtNgayGhiPhieu.setText(ChuyenDoi.SoString(arr.get(0).getNgayGhiPhieu()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlThongTinSP = new javax.swing.JPanel();
        lblMaSP = new javax.swing.JLabel();
        txtMaPhong = new javax.swing.JTextField();
        lblTenSP = new javax.swing.JLabel();
        txtTenPhong = new javax.swing.JTextField();
        txtViTri = new javax.swing.JTextField();
        lblDonViTinh = new javax.swing.JLabel();
        lblLoaiSP = new javax.swing.JLabel();
        cbbTinhTrang = new javax.swing.JComboBox<>();
        lblMoTa = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();
        pnlNutBam = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        txtTuKhoaTimKiem = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnXuatFile = new javax.swing.JButton();
        btnDocFile = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPhong = new javax.swing.JTable();
        txtTenPhongTro = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtChuPhongTro = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JLabel();
        btnSuaTTPhongTro = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtGiaPhong = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtGiaDien = new javax.swing.JLabel();
        txtGiaNuoc = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNgayGhiPhieu = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnSuaBangGia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(229, 255, 255));
        setUndecorated(true);

        pnlThongTinSP.setBackground(new java.awt.Color(255, 255, 255));
        pnlThongTinSP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));

        lblMaSP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMaSP.setForeground(new java.awt.Color(255, 102, 0));
        lblMaSP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMaSP.setText("Mã phòng");

        lblTenSP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTenSP.setForeground(new java.awt.Color(255, 102, 0));
        lblTenSP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTenSP.setText("Tên phòng");

        lblDonViTinh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDonViTinh.setForeground(new java.awt.Color(255, 102, 0));
        lblDonViTinh.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDonViTinh.setText("Vị trí");

        lblLoaiSP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblLoaiSP.setForeground(new java.awt.Color(255, 102, 0));
        lblLoaiSP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLoaiSP.setText("Tình trạng");

        cbbTinhTrang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trống", "Đã cho thuê" }));

        lblMoTa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMoTa.setForeground(new java.awt.Color(255, 102, 0));
        lblMoTa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMoTa.setText("Ghi chú");

        txtGhiChu.setColumns(20);
        txtGhiChu.setRows(5);
        jScrollPane1.setViewportView(txtGhiChu);

        javax.swing.GroupLayout pnlThongTinSPLayout = new javax.swing.GroupLayout(pnlThongTinSP);
        pnlThongTinSP.setLayout(pnlThongTinSPLayout);
        pnlThongTinSPLayout.setHorizontalGroup(
            pnlThongTinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinSPLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pnlThongTinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThongTinSPLayout.createSequentialGroup()
                        .addGroup(pnlThongTinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTenSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMoTa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlThongTinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlThongTinSPLayout.createSequentialGroup()
                                .addComponent(txtTenPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblLoaiSP)
                                .addGap(18, 18, 18)
                                .addComponent(cbbTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlThongTinSPLayout.createSequentialGroup()
                        .addComponent(lblMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblDonViTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtViTri, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlThongTinSPLayout.setVerticalGroup(
            pnlThongTinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinSPLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlThongTinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaSP)
                    .addComponent(txtMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtViTri, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDonViTinh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlThongTinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTenSP)
                    .addComponent(cbbTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLoaiSP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlThongTinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMoTa))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pnlNutBam.setBackground(new java.awt.Color(255, 255, 255));
        pnlNutBam.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51)));

        btnThem.setBackground(new java.awt.Color(0, 153, 0));
        btnThem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnThoat.setBackground(new java.awt.Color(255, 0, 0));
        btnThoat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnThoat.setForeground(new java.awt.Color(255, 255, 255));
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(255, 102, 0));
        btnXoa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(0, 153, 0));
        btnSua.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        txtTuKhoaTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTuKhoaTimKiemKeyReleased(evt);
            }
        });

        jLabel1.setText("Nhập từ khóa");

        btnXuatFile.setBackground(new java.awt.Color(0, 204, 204));
        btnXuatFile.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnXuatFile.setForeground(new java.awt.Color(255, 255, 255));
        btnXuatFile.setText("Xuất Excel");
        btnXuatFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatFileActionPerformed(evt);
            }
        });

        btnDocFile.setBackground(new java.awt.Color(0, 51, 255));
        btnDocFile.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDocFile.setForeground(new java.awt.Color(255, 255, 255));
        btnDocFile.setText("Đọc Excel");

        javax.swing.GroupLayout pnlNutBamLayout = new javax.swing.GroupLayout(pnlNutBam);
        pnlNutBam.setLayout(pnlNutBamLayout);
        pnlNutBamLayout.setHorizontalGroup(
            pnlNutBamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNutBamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtTuKhoaTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXuatFile, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDocFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        pnlNutBamLayout.setVerticalGroup(
            pnlNutBamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNutBamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNutBamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlNutBamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTuKhoaTimKiem)
                        .addComponent(btnXuatFile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDocFile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addGroup(pnlNutBamLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlNutBamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        tblPhong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã phòng", "Tên phòng", "Vị trí", "Tình trạng", "Ghi chú"
            }
        ));
        tblPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPhongMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPhong);

        txtTenPhongTro.setBackground(new java.awt.Color(204, 204, 255));
        txtTenPhongTro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtTenPhongTro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTenPhongTro.setText("txtTenPhongTro");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));

        txtChuPhongTro.setText("txtChuPhongTro");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Số điện thoại :");

        txtSDT.setText("txtSDT");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Địa chỉ :");

        txtDiaChi.setText("txtDiaChi");

        btnSuaTTPhongTro.setBackground(new java.awt.Color(153, 255, 153));
        btnSuaTTPhongTro.setText("Sửa");
        btnSuaTTPhongTro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaTTPhongTroActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Chủ trọ :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtChuPhongTro, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSuaTTPhongTro, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtChuPhongTro)
                    .addComponent(jLabel3)
                    .addComponent(txtSDT)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiaChi)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(btnSuaTTPhongTro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Giá phòng :");

        txtGiaPhong.setText("txtGiaPhong");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Giá điện :");

        txtGiaDien.setText("txtGiaDien");

        txtGiaNuoc.setText("txtGiaDien");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Giá nước :");

        txtNgayGhiPhieu.setText("txtNgayGhiPhieu");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Ngày ghi phiếu :");

        jLabel6.setText("Đơn vị : VND");

        btnSuaBangGia.setBackground(new java.awt.Color(153, 255, 153));
        btnSuaBangGia.setText("Sửa");
        btnSuaBangGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaBangGiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGiaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGiaDien, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtGiaNuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNgayGhiPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSuaBangGia, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5)
                .addComponent(txtGiaPhong)
                .addComponent(jLabel7)
                .addComponent(txtGiaDien)
                .addComponent(jLabel10)
                .addComponent(txtGiaNuoc)
                .addComponent(jLabel11)
                .addComponent(txtNgayGhiPhieu)
                .addComponent(jLabel6))
            .addComponent(btnSuaBangGia, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlThongTinSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlNutBam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtTenPhongTro, javax.swing.GroupLayout.PREFERRED_SIZE, 953, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTenPhongTro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlThongTinSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlNutBam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTuKhoaTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTuKhoaTimKiemKeyReleased
        // TODO add your handling code here:
        String tukhoa = txtTuKhoaTimKiem.getText();
        ArrayList<Phong> arrSP = BLL.BLLPhong.FindByName(tukhoa);
        BLL.BLLPhong.doDataTable(arrSP, tblPhong);
    }//GEN-LAST:event_txtTuKhoaTimKiemKeyReleased

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        String MaPhong = txtMaPhong.getText();//10
        String TenPhong = txtTenPhong.getText();//60
        String ViTri = txtViTri.getText();//15
        String GhiChu = txtGhiChu.getText();//15]]
        boolean TinhTrang = true;
        if (cbbTinhTrang.getSelectedIndex() == 0) {
            TinhTrang = false;
        }

        if (MaPhong.equals("") || TenPhong.equals("")) {
            ThongBao.ThongBaoDonGian("Thông báo", "Vui lòng kiểm tra lại thông tin!");
            return;
        }
        try {
            BLL.BLLPhong.Insert(new Phong(MaPhong, TenPhong, ViTri, GhiChu, TinhTrang));
            ThongBao.ThongBaoDonGian("Thông báo", "Đã thêm");
        } catch (Exception e) {
            ThongBao.ThongBaoDonGian("Thông báo", "Vui lòng kiểm tra lại thông tin!");
        }
        
        loadTT();

//        ArrayList<LoaiSanPham> arr = BLL.BLLLoaiSanPham.GetAll();
//        for (LoaiSanPham i : arr) {
//            if (cbbTinhTrang.getSelectedItem().equals(i.getTenLoai())) {
//                MaLoaiSP = i.getMaLoaiSP();
//            }
//            System.out.println(cbbTinhTrang.getSelectedItem() + " " + i.getTenLoai() + " " + i.getMaLoaiSP());
//
//        }
//        if(MaSP.equals("")||cbbTinhTrang.getSelectedIndex()==0){
//            return;
//        }
//
//        String MoTa = txtGhiChu.getText();//225
//        System.out.println(MaSP + TenSP + " " + MaLoaiSP + MoTa);

    }//GEN-LAST:event_btnThemActionPerformed

    private void tblPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPhongMouseClicked
//         TODO add your handling code here:
        int indexRow = tblPhong.getSelectedRow();
        txtMaPhong.setText(tblPhong.getValueAt(indexRow, 1).toString());
        txtTenPhong.setText(tblPhong.getValueAt(indexRow, 2).toString());
        if (tblPhong.getValueAt(indexRow, 3) != null) {
            txtViTri.setText(tblPhong.getValueAt(indexRow, 3).toString());
        } else {
            txtViTri.setText("");
        }
        if (null != tblPhong.getValueAt(indexRow, 5)) {
            txtGhiChu.setText(tblPhong.getValueAt(indexRow, 5).toString());
        } else {
            txtGhiChu.setText("");
        }
        if (tblPhong.getValueAt(indexRow, 4).toString() == "Trống") {
            cbbTinhTrang.setSelectedIndex(0);
        } else {
            cbbTinhTrang.setSelectedIndex(1);
        }
//        String TenLoaiSP=tblPhong.getValueAt(indexRow, 8).toString();
//        if (tblPhong.getValueAt(indexRow, 9) != null) {
//            txtGhiChu.setText(tblPhong.getValueAt(indexRow, 9).toString());
//        }else{
//            txtGhiChu.setText("");
//        }
    }//GEN-LAST:event_tblPhongMouseClicked

    private void btnSuaTTPhongTroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaTTPhongTroActionPerformed
        // TODO add your handling code here:
        jdlUpdTTNhaTro jdl = new jdlUpdTTNhaTro(this, true);
        jdl.setVisible(true);
        loadTT();
    }//GEN-LAST:event_btnSuaTTPhongTroActionPerformed

    private void btnSuaBangGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaBangGiaActionPerformed
        // TODO add your handling code here:
        jdlUpdTTBangGia jdl = new jdlUpdTTBangGia(this, true);
        jdl.setVisible(true);
        loadTT();
    }//GEN-LAST:event_btnSuaBangGiaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        String MaPhong = txtMaPhong.getText();//10
        String TenPhong = txtTenPhong.getText();//60
        String ViTri = txtViTri.getText();//15
        String GhiChu = txtGhiChu.getText();//15]]
        boolean TinhTrang = true;
        if (cbbTinhTrang.getSelectedIndex() == 0) {
            TinhTrang = false;
        }

        if (MaPhong.equals("") || TenPhong.equals("")) {
            return;
        }
        try {
            BLL.BLLPhong.Update(new Phong(MaPhong, TenPhong, ViTri, GhiChu, TinhTrang));
            ThongBao.ThongBaoDonGian("Thông báo", "Đã cập nhật");
        } catch (Exception e) {
            ThongBao.ThongBaoDonGian("Thông báo", "Vui lòng kiểm tra lại thông tin!");
        }
        loadTT();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        ThongBao.ThongBaoDonGian("Cảnh báo", "Không được xóa phòng!");
    }//GEN-LAST:event_btnXoaActionPerformed

//    private void XuatExcel(String duongDan) {
//        try {
//            XSSFWorkbook workBook = new XSSFWorkbook();
//            XSSFSheet sheet = workBook.createSheet("Danh sách nhân viên");
//            XSSFRow row = null;
//            Cell cell = null;
//            row = sheet.createRow(0);
//            cell = row.createCell(0, CellType.STRING);
//            cell.setCellValue("STT");
//            cell = row.createCell(1, CellType.STRING);
//            cell.setCellValue("Mã phòng");
//            cell = row.createCell(2, CellType.STRING);
//            cell.setCellValue("Tên phòng");
//            cell = row.createCell(3, CellType.STRING);
//            cell.setCellValue("Vị trí");
//            cell = row.createCell(4, CellType.STRING);
//            cell.setCellValue("Tình trạng");
//            cell = row.createCell(5, CellType.STRING);
//            cell.setCellValue("Ghi chú");
////            ArrayList<NhanVien> arrNV = BLL.BLLNhanVien.GetAll();
//            for (int i = 0; i < tblPhong.getRowCount(); i++) {
//                row = sheet.createRow(1 + i);
//                cell = row.createCell(0, CellType.NUMERIC);
//                cell.setCellValue(i + 1);
//
//                cell = row.createCell(1, CellType.STRING);
//                cell.setCellValue(tblPhong.getValueAt(i, 1).toString() + " ");
//
//                cell = row.createCell(2, CellType.STRING);
//                cell.setCellValue(tblPhong.getValueAt(i, 2).toString() + " ");
//                if (tblPhong.getValueAt(i, 3) != null) {
//                    cell = row.createCell(3, CellType.STRING);
//                    cell.setCellValue(tblPhong.getValueAt(i, 3).toString() + " ");
//                }
//
//                cell = row.createCell(4, CellType.STRING);
//                cell.setCellValue(tblPhong.getValueAt(i, 4).toString() + " ");
//                if (tblPhong.getValueAt(i, 5) != null) {
//                    cell = row.createCell(5, CellType.BOOLEAN);
//                    cell.setCellValue(tblPhong.getValueAt(i, 5).toString() + " ");
//                }
//
////                CellStyle cellStyle = workBook.createCellStyle(); 
////                CreationHelper createHelper = workBook.getCreationHelper(); 
////                cellStyle.setDataFormat(  
////                createHelper.createDataFormat().getFormat("dd/MM/yyyy"));  
////                cell.setCellStyle(cellStyle);  
//            }
//
//            for(int columnIndex = 0; columnIndex < 6;columnIndex++)
//            {
//                sheet.autoSizeColumn(columnIndex);//Tự động điều chỉnh độ rộng của cột vừa đủ để hiển thị đầy đủ nội dung
//            }
//            File file = new File(duongDan);
//            try {
//                FileOutputStream fos = new FileOutputStream(file);
//                workBook.write(fos);
//                fos.close();
//                ThongBao.ThongBaoDonGian("Thông báo", "In thành công");
//            } catch (Exception e) {
//                ThongBao.ThongBaoDonGian("Thông báo", "Thất bại 2");
//            }
//        } catch (Exception e) {
//            ThongBao.ThongBaoDonGian("Thông báo", "Thất bại 1");
//            System.out.println(e.getMessage());
//        }
//
//    }

    private void btnXuatFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatFileActionPerformed
        // TODO add your handling code here:
//        JFileChooser fc = new JFileChooser("D:\\");
//        fc.setFileFilter(new FileNameExtensionFilter("*.xlsx", "xlsx"));
//        fc.setDialogTitle("Open File");
//        fc.showSaveDialog(null);
//        try {
//            File file = fc.getSelectedFile();
//            if (file.equals(null)) {
//                return;
//            }
//            XuatExcel(file + ".xlsx");
//        } catch (Exception e) {
//        }
        ArrayList<String> TBHeader = new ArrayList<>();
        TBHeader.add("STT");
        TBHeader.add("Mã phòng");
        TBHeader.add("Tên phòng");
        TBHeader.add("Vị trí");
        TBHeader.add("Tình trạng");
        TBHeader.add("Ghi chú");
        XuatExcel.XuatExcelTB(tblPhong, TBHeader);
    }//GEN-LAST:event_btnXuatFileActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmQLPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmQLPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmQLPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmQLPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new frmQLPhong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDocFile;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnSuaBangGia;
    private javax.swing.JButton btnSuaTTPhongTro;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXuatFile;
    private javax.swing.JComboBox<String> cbbTinhTrang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDonViTinh;
    private javax.swing.JLabel lblLoaiSP;
    private javax.swing.JLabel lblMaSP;
    private javax.swing.JLabel lblMoTa;
    private javax.swing.JLabel lblTenSP;
    private javax.swing.JPanel pnlNutBam;
    private javax.swing.JPanel pnlThongTinSP;
    private javax.swing.JTable tblPhong;
    private javax.swing.JLabel txtChuPhongTro;
    private javax.swing.JLabel txtDiaChi;
    private javax.swing.JTextArea txtGhiChu;
    private javax.swing.JLabel txtGiaDien;
    private javax.swing.JLabel txtGiaNuoc;
    private javax.swing.JLabel txtGiaPhong;
    private javax.swing.JTextField txtMaPhong;
    private javax.swing.JLabel txtNgayGhiPhieu;
    private javax.swing.JLabel txtSDT;
    private javax.swing.JTextField txtTenPhong;
    private javax.swing.JLabel txtTenPhongTro;
    private javax.swing.JTextField txtTuKhoaTimKiem;
    private javax.swing.JTextField txtViTri;
    // End of variables declaration//GEN-END:variables
}
