/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import DTO.DaiDienThue;
import DTO.Phong;
import DTO.ThanNhanThue;
import helper.ChuyenDoi;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import helper.ThongBao;
import helper.XuatExcel;
import java.io.BufferedOutputStream;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDate;
import javax.swing.JFileChooser;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.examples.xwpf.usermodel.SimpleTable;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author cuong
 */
public class pnlQLThuePhong extends javax.swing.JPanel {

    /**
     * Creates new form pnlQLNhanVien
     */
    public pnlQLThuePhong() {
        initComponents();
        loadTT();
    }

    public void loadTT() {
        ArrayList<Phong> arr = BLL.BLLPhong.GetAll();
        BLL.BLLPhong.doDataTableThuePhong(arr, tbTTPhongThue);
        BLL.BLLPhong.doComboBox(arr, cbPhong);
        lblLoaiSP1.setVisible(false);
        rdGioiTinh.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pnlThongTinSP = new javax.swing.JPanel();
        lblMaSP = new javax.swing.JLabel();
        lblTenSP = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        lblMaSP1 = new javax.swing.JLabel();
        lblGiaNhap = new javax.swing.JLabel();
        lblGiaBan = new javax.swing.JLabel();
        lblLoaiSP = new javax.swing.JLabel();
        lblLoaiSP1 = new javax.swing.JLabel();
        rdGioiTinh = new javax.swing.JRadioButton();
        txtQueQuan = new javax.swing.JTextField();
        dateNgaySinh = new com.toedter.calendar.JDateChooser();
        dateNgayBDThue = new com.toedter.calendar.JDateChooser();
        txtMaNguoiDaiDien = new javax.swing.JTextField();
        txtCMND = new javax.swing.JTextField();
        lblMaSP2 = new javax.swing.JLabel();
        lblLoaiSP2 = new javax.swing.JLabel();
        rdVaiTro = new javax.swing.JRadioButton();
        cbPhong = new javax.swing.JComboBox<>();
        lblGiaBan1 = new javax.swing.JLabel();
        dateNgayTP = new com.toedter.calendar.JDateChooser();
        pnlNutBam = new javax.swing.JPanel();
        btnXuatFile = new javax.swing.JButton();
        btnTraPhong = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtTuKhoa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTTPhongThue = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbTTNguoiThue = new javax.swing.JTable();
        txtTenPhongtb = new javax.swing.JLabel();
        txtMaNDDtb = new javax.swing.JLabel();

        setBackground(new java.awt.Color(229, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản lý Thuê Phòng");

        pnlThongTinSP.setBackground(new java.awt.Color(229, 255, 255));
        pnlThongTinSP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));

        lblMaSP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMaSP.setForeground(new java.awt.Color(255, 102, 0));
        lblMaSP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMaSP.setText("Mã người đại diện");

        lblTenSP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTenSP.setForeground(new java.awt.Color(255, 102, 0));
        lblTenSP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTenSP.setText("Tên ");

        lblMaSP1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMaSP1.setForeground(new java.awt.Color(255, 102, 0));
        lblMaSP1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMaSP1.setText("Quê quán");

        lblGiaNhap.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblGiaNhap.setForeground(new java.awt.Color(255, 102, 0));
        lblGiaNhap.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGiaNhap.setText("Ngày sinh");

        lblGiaBan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblGiaBan.setForeground(new java.awt.Color(255, 102, 0));
        lblGiaBan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGiaBan.setText("Ngày bắt đầu thuê");

        lblLoaiSP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblLoaiSP.setForeground(new java.awt.Color(255, 102, 0));
        lblLoaiSP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLoaiSP.setText("CMND");

        lblLoaiSP1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblLoaiSP1.setForeground(new java.awt.Color(255, 102, 0));
        lblLoaiSP1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLoaiSP1.setText("Giới tính");

        rdGioiTinh.setText("Nam");

        dateNgaySinh.setDateFormatString("yyy-MM-dd");

        dateNgayBDThue.setDateFormatString("yyy-MM-dd");

        lblMaSP2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMaSP2.setForeground(new java.awt.Color(255, 102, 0));
        lblMaSP2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMaSP2.setText("Phòng:");

        lblLoaiSP2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblLoaiSP2.setForeground(new java.awt.Color(255, 102, 0));
        lblLoaiSP2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLoaiSP2.setText("Vai trò");

        rdVaiTro.setText("Người đại diện");

        cbPhong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblGiaBan1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblGiaBan1.setForeground(new java.awt.Color(255, 102, 0));
        lblGiaBan1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGiaBan1.setText("Ngày trả phòng");

        dateNgayTP.setDateFormatString("yyy-MM-dd");

        javax.swing.GroupLayout pnlThongTinSPLayout = new javax.swing.GroupLayout(pnlThongTinSP);
        pnlThongTinSP.setLayout(pnlThongTinSPLayout);
        pnlThongTinSPLayout.setHorizontalGroup(
            pnlThongTinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinSPLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(pnlThongTinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlThongTinSPLayout.createSequentialGroup()
                        .addComponent(lblLoaiSP1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rdGioiTinh))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlThongTinSPLayout.createSequentialGroup()
                        .addComponent(lblLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCMND))
                    .addGroup(pnlThongTinSPLayout.createSequentialGroup()
                        .addComponent(lblTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTen))
                    .addGroup(pnlThongTinSPLayout.createSequentialGroup()
                        .addGroup(pnlThongTinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMaSP)
                            .addComponent(lblMaSP2))
                        .addGap(18, 18, 18)
                        .addGroup(pnlThongTinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaNguoiDaiDien, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(cbPhong, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(69, 69, 69)
                .addGroup(pnlThongTinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlThongTinSPLayout.createSequentialGroup()
                        .addGroup(pnlThongTinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblGiaBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblGiaNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblGiaBan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlThongTinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dateNgayBDThue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dateNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateNgayTP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlThongTinSPLayout.createSequentialGroup()
                        .addComponent(lblMaSP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(txtQueQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlThongTinSPLayout.createSequentialGroup()
                        .addComponent(lblLoaiSP2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rdVaiTro)))
                .addContainerGap(207, Short.MAX_VALUE))
        );
        pnlThongTinSPLayout.setVerticalGroup(
            pnlThongTinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinSPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlThongTinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaSP2)
                    .addComponent(lblLoaiSP2)
                    .addComponent(rdVaiTro)
                    .addComponent(cbPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(pnlThongTinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlThongTinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblMaSP)
                        .addComponent(txtMaNguoiDaiDien, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblGiaNhap))
                    .addComponent(dateNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlThongTinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThongTinSPLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlThongTinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTenSP)
                            .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMaSP1)
                            .addComponent(txtQueQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlThongTinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLoaiSP)
                            .addGroup(pnlThongTinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblGiaBan))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlThongTinSPLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(dateNgayBDThue, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlThongTinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThongTinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblLoaiSP1)
                        .addComponent(rdGioiTinh))
                    .addComponent(dateNgayTP, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGiaBan1))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pnlNutBam.setBackground(new java.awt.Color(229, 255, 255));
        pnlNutBam.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51)));

        btnXuatFile.setBackground(new java.awt.Color(0, 153, 0));
        btnXuatFile.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnXuatFile.setForeground(new java.awt.Color(255, 255, 255));
        btnXuatFile.setText("Xuất file");
        btnXuatFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatFileActionPerformed(evt);
            }
        });

        btnTraPhong.setBackground(new java.awt.Color(255, 0, 0));
        btnTraPhong.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnTraPhong.setForeground(new java.awt.Color(255, 255, 255));
        btnTraPhong.setText("Trả phòng");
        btnTraPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraPhongActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(255, 102, 0));
        btnXoa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(0, 153, 0));
        btnSua.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnThem.setBackground(new java.awt.Color(0, 153, 0));
        btnThem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNutBamLayout = new javax.swing.GroupLayout(pnlNutBam);
        pnlNutBam.setLayout(pnlNutBamLayout);
        pnlNutBamLayout.setHorizontalGroup(
            pnlNutBamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNutBamLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(btnXuatFile, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTraPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        pnlNutBamLayout.setVerticalGroup(
            pnlNutBamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNutBamLayout.createSequentialGroup()
                .addGroup(pnlNutBamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNutBamLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnXuatFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlNutBamLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(pnlNutBamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTraPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlNutBamLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(229, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));

        txtTuKhoa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTuKhoaKeyReleased(evt);
            }
        });

        tbTTPhongThue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã phòng", "Phòng", "Trạng thái", "Đại diện thuê"
            }
        ));
        tbTTPhongThue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTTPhongThueMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbTTPhongThue);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtTuKhoa)
                        .addGap(184, 184, 184)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTuKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(229, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));

        tbTTNguoiThue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        tbTTNguoiThue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tên", "CMND", "Ngày sinh", "Quê quán", "Ngày bắt đầu thuê"
            }
        ));
        tbTTNguoiThue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTTNguoiThueMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbTTNguoiThue);

        txtTenPhongtb.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtTenPhongtb.setText("txtTenPhong");

        txtMaNDDtb.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtMaNDDtb.setText("txtMaNDD");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 937, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtTenPhongtb, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(txtMaNDDtb, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenPhongtb)
                    .addComponent(txtMaNDDtb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlNutBam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlThongTinSP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(pnlThongTinSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlNutBam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

//    public boolean CheckDataThueInsert() {
//        ArrayList<DaiDienThue> arr = BLL.BLLDaiDienThue.FindByMaNDD((String) cbPhong.getSelectedItem());
//        isThue();
//        for (DaiDienThue i : arr) {
//            if (i.getMaNguoiDaiDien()) {
//
//            }
//        }
//    }
    public boolean isThue() {
        ArrayList<Phong> arrPT = BLL.BLLPhong.FindByTingTrang();
        for (Phong i : arrPT) {
            if (cbPhong.getSelectedItem().toString().equals(i.getTenPhong())) {
                ThongBao.ThongBaoDonGian("Thông báo", "Phòng đã có người thuê!");
                return false;
            } else {
                ThongBao.ThongBaoDonGian("Thông báo", "ok");
            }
        }
        return true;
    }

    public String reMaPhong(String tenPhong) {
        ArrayList<Phong> arrPT = BLL.BLLPhong.GetAll();
        for (Phong i : arrPT) {
            if (tenPhong.equals(i.getTenPhong())) {
                return i.getMaPhong();
            }
        }
        return null;
    }

    public boolean ischeckTTNDD(int ChucNang) {
//        ArrayList<Phong> phong = BLL.BLLPhong.FindByName(cbPhong.getSelectedItem().toString());
//        if (phong.size() > 0) {
            ArrayList<DaiDienThue> ddt = BLL.BLLDaiDienThue.FindByMaNDD(txtMaNguoiDaiDien.getText());
            if (ddt.size() > 0) {
                cbPhong.getSelectedItem();
//                ThongBao.ThongBaoDonGian("Thông báo", "Chưa thuê");
                String maPhong = cbPhong.getSelectedItem() + "";
                String maNDD = txtMaNguoiDaiDien.getText();
                String ten = txtTen.getText();
                String CMND = txtCMND.getText();
                String queQuan = txtQueQuan.getText();
                Date ngSinh = dateNgaySinh.getDate();
                System.out.println(maNDD + " " + reMaPhong(maPhong) + " " + ten + " " + CMND + " " + ngSinh + " " + queQuan + " ");
                if(ChucNang==1){
                    BLL.BLLThanNhanThue.Insert(new ThanNhanThue(maNDD, ten, CMND, ngSinh, queQuan));
                }else{
                    BLL.BLLThanNhanThue.Update(new ThanNhanThue(maNDD, ten, CMND, ngSinh, queQuan));
                }
                
                return true;
            }else{
                
            }
//        }

        return false;
    }


    private void btnXuatFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatFileActionPerformed
        // TODO add your handling code here:
        ArrayList<String> TBHeader = new ArrayList<>();
        TBHeader.add("Tên");
        TBHeader.add("CMND");
        TBHeader.add("Ngày sinh");
        TBHeader.add("Quê quán");
        TBHeader.add("Ngày thuê");
        XuatExcel.XuatExcelTB(tbTTNguoiThue, TBHeader);

    }//GEN-LAST:event_btnXuatFileActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        if (txtMaNguoiDaiDien.getText().equals("") || txtTen.getText().equals("")  || txtQueQuan.getText().equals("") || dateNgaySinh.getDate().equals("")) {
            ThongBao.ThongBaoDonGian("Thông báo", "Dữ liệu trống!");
            return;
        }
        if (rdVaiTro.isSelected()) {//người đại diện
            if (isThue()) {
                cbPhong.getSelectedItem();
                String maPhong = cbPhong.getSelectedItem() + "";
                String maNDD = txtMaNguoiDaiDien.getText();
                String ten = txtTen.getText();
                String CMND = txtCMND.getText();
                Date ngayBDT = dateNgayBDThue.getDate();
                String queQuan = txtQueQuan.getText();
                Date ngSinh = dateNgaySinh.getDate();
                System.out.println(maNDD + " " + reMaPhong(maPhong) + " " + ten + " " + CMND + " " + ngSinh + " " + queQuan + " " + ngayBDT);
                BLL.BLLDaiDienThue.UpdateTT(new DaiDienThue(maNDD, reMaPhong(maPhong), ten, CMND, ngSinh, queQuan, ngayBDT));
//                jdlDienNuoc jdl = new jdlDienNuoc(null, true);
//                jdl.setVisible(true);
                loadTTPT();
            } else {
                return;
            }

        } else {//thân nhân
            ischeckTTNDD(2);
            loadTTPT();
        }

    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int dongDangChon = tbTTNguoiThue.getSelectedRow();
        if (dongDangChon == 0) {
            ThongBao.ThongBaoDonGian("Thông Báo", "Không thể xóa người đại diện!");
        }
        if (dongDangChon < 0) {
            ThongBao.ThongBaoDonGian("Thông Báo", "Bạn chưa chọn đối tượng cần xóa");
        } else {
            int XacNhan = JOptionPane.showConfirmDialog(null, "Bạn có chắc xóa không?", "Thông báo xác nhận", JOptionPane.OK_CANCEL_OPTION);
            if (XacNhan == JOptionPane.CANCEL_OPTION) {
                return;
            }
        }
        //Lấy danh sách các sp  cần xóa
        int dongCanXoa[] = tbTTNguoiThue.getSelectedRows();

        for (int i = 0; i < dongCanXoa.length; i++) {
            ArrayList<DaiDienThue> ID = BLL.BLLDaiDienThue.FindByMaNDD(txtMaNguoiDaiDien.getText());
            String ten = tbTTNguoiThue.getValueAt(dongCanXoa[i], 0).toString();
            BLL.BLLThanNhanThue.Delete(ID.get(0).getMaNguoiDaiDien(), ten);
        }
        loadTTPT();
    }//GEN-LAST:event_btnXoaActionPerformed

    public void loadTTPT() {
        try {
            int indexRow = tbTTPhongThue.getSelectedRow();
        if (!tbTTPhongThue.getValueAt(indexRow, 2).toString().equals("Trống")) {
//            ThongBao.ThongBaoDonGian("Thông báo", "lo");
            ArrayList<DaiDienThue> arr = BLL.BLLDaiDienThue.FindDDThue(tbTTPhongThue.getValueAt(indexRow, 0).toString());
            ArrayList<ThanNhanThue> arrTN = BLL.BLLThanNhanThue.FindByMaNDD(tbTTPhongThue.getValueAt(indexRow, 3).toString());
            BLL.BLLDaiDienThue.doDataTableTTThue(arr, tbTTNguoiThue);
            BLL.BLLThanNhanThue.doDataTableTTThue(arrTN, tbTTNguoiThue);
            txtMaNDDtb.setText(arr.get(0).getMaNguoiDaiDien());
            txtTenPhongtb.setText(tbTTPhongThue.getValueAt(indexRow, 1).toString());
        } else {
            DefaultTableModel tbModel = (DefaultTableModel) tbTTNguoiThue.getModel();
            tbModel.setRowCount(0);
            txtMaNDDtb.setText("");
            txtTenPhongtb.setText("");
        }
        } catch (Exception e) {
        }
        
    }
    private void tbTTPhongThueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTTPhongThueMouseClicked
        // TODO add your handling code here:
        loadTTPT();
    }//GEN-LAST:event_tbTTPhongThueMouseClicked

    private void tbTTNguoiThueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTTNguoiThueMouseClicked
        // TODO add your handling code here:
        int indexRow = tbTTNguoiThue.getSelectedRow();
        txtMaNguoiDaiDien.setText(txtMaNDDtb.getText());
        BLL.BLLPhong.HienThiPhongCBB(cbPhong, txtTenPhongtb.getText());
        System.out.println(txtTenPhongtb.getText());
        if (indexRow == 0) {
            rdVaiTro.setSelected(true);
        } else {
            rdVaiTro.setSelected(false);
        }
        txtTen.setText(tbTTNguoiThue.getValueAt(indexRow, 0).toString());
        if (tbTTNguoiThue.getValueAt(indexRow, 1) == null) {
            txtCMND.setText("");
        } else {
            txtCMND.setText(tbTTNguoiThue.getValueAt(indexRow, 1).toString());
        }
        dateNgaySinh.setDate(ChuyenDoi.LayNgayDate(tbTTNguoiThue.getValueAt(indexRow, 2).toString()));
        txtQueQuan.setText(tbTTNguoiThue.getValueAt(indexRow, 3).toString());
        dateNgayBDThue.setDate(ChuyenDoi.LayNgayDate(tbTTNguoiThue.getValueAt(0, 4).toString()));
    }//GEN-LAST:event_tbTTNguoiThueMouseClicked

    private void btnTraPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraPhongActionPerformed
        // TODO add your handling code here:
        
        int indexRow = tbTTNguoiThue.getSelectedRow();
        txtMaNguoiDaiDien.setText(txtMaNDDtb.getText());
        String maNDD = txtMaNDDtb.getText();
        try {
            BLL.BLLDaiDienThue.UpdateTraPhong(maNDD);
            ThongBao.ThongBaoDonGian("Thông báo", "Đã trả!");
            loadTT();
        } catch (Exception e) {
            ThongBao.ThongBaoDonGian("Thông báo", "Vui lòng kiểm tra lại!");
        }
    }//GEN-LAST:event_btnTraPhongActionPerformed

    private void txtTuKhoaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTuKhoaKeyReleased
        // TODO add your handling code here:
        String tukhoa = txtTuKhoa.getText();
        ArrayList<Phong> arrP = BLL.BLLPhong.FindByName(tukhoa);
        BLL.BLLPhong.doDataTableThuePhong(arrP, tbTTPhongThue);
    }//GEN-LAST:event_txtTuKhoaKeyReleased

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        if (txtMaNguoiDaiDien.getText().equals("") || txtTen.getText().equals("")  || txtQueQuan.getText().equals("") || dateNgaySinh.getDate().equals("")) {
            ThongBao.ThongBaoDonGian("Thông báo", "Dữ liệu trống!");
            return;
        }
        if (rdVaiTro.isSelected()) {//người đại diện
            if (isThue()) {
                cbPhong.getSelectedItem();
                String maPhong = cbPhong.getSelectedItem() + "";
                String maNDD = txtMaNguoiDaiDien.getText();
                String ten = txtTen.getText();
                String CMND = txtCMND.getText();
                Date ngayBDT = dateNgayBDThue.getDate();
                String queQuan = txtQueQuan.getText();
                Date ngSinh = dateNgaySinh.getDate();
                Date ngTraPhong = dateNgayTP.getDate();
                System.out.println(maNDD + " " + reMaPhong(maPhong) + " " + ten + " " + CMND + " " + ngSinh + " " + queQuan + " " + ngayBDT);
                BLL.BLLDaiDienThue.Insert(new DaiDienThue(maNDD, reMaPhong(maPhong), ten, CMND, ngSinh, queQuan, ngayBDT,ngTraPhong));
                jdlDienNuoc jdl = new jdlDienNuoc(null, true);
                jdl.setVisible(true);
                loadTTPT();
            } else {
                return;
            }

        } else {//thân nhân
            ischeckTTNDD(1);
            loadTTPT();
        }
    }//GEN-LAST:event_btnThemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTraPhong;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXuatFile;
    private javax.swing.JComboBox<String> cbPhong;
    private com.toedter.calendar.JDateChooser dateNgayBDThue;
    private com.toedter.calendar.JDateChooser dateNgaySinh;
    private com.toedter.calendar.JDateChooser dateNgayTP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblGiaBan;
    private javax.swing.JLabel lblGiaBan1;
    private javax.swing.JLabel lblGiaNhap;
    private javax.swing.JLabel lblLoaiSP;
    private javax.swing.JLabel lblLoaiSP1;
    private javax.swing.JLabel lblLoaiSP2;
    private javax.swing.JLabel lblMaSP;
    private javax.swing.JLabel lblMaSP1;
    private javax.swing.JLabel lblMaSP2;
    private javax.swing.JLabel lblTenSP;
    private javax.swing.JPanel pnlNutBam;
    private javax.swing.JPanel pnlThongTinSP;
    private javax.swing.JRadioButton rdGioiTinh;
    private javax.swing.JRadioButton rdVaiTro;
    private javax.swing.JTable tbTTNguoiThue;
    private javax.swing.JTable tbTTPhongThue;
    private javax.swing.JTextField txtCMND;
    private javax.swing.JLabel txtMaNDDtb;
    private javax.swing.JTextField txtMaNguoiDaiDien;
    private javax.swing.JTextField txtQueQuan;
    private javax.swing.JTextField txtTen;
    private javax.swing.JLabel txtTenPhongtb;
    private javax.swing.JTextField txtTuKhoa;
    // End of variables declaration//GEN-END:variables
}
